version: "3"

services:
  main:
    container_name: backend
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ~/.npmrc:/app/.npmrc
    ports:
      - 443:443
    restart: always
    # network: htts-portal

    # depends_on: 
    #   https-portal
  # https-portal:
  #   container_name: https-portal
  #   image: steveltn/https-portal:1
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   links:
  #     - main
  #   restart: always
  #   environment:
  #     STAGE: 'production'