version: "3"

services:
  main:
    container_name: backend
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ~/.npmrc:/app/.npmrc
    # ports:
    #   - 5000:5000
    restart: always
    # depends_on: 
    #   https-portal
  https-portal:
    container_name: https-portal
    image: steveltn/https-portal:1
    ports:
      - '80:5000'
      - '443:5000'
    links:
      - main
    restart: always