version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - main
    restart: always
  main:
    container_name: backend
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ~/.npmrc:/app/.npmrc
    ports:
      - 443:443
      - 9229:9229
    restart: always
    depends_on:
      https-portal:
        condition: service_healthy